### ISSUE TITLE
Update Readme.md and Add New Members in the Contributors Section

### ISSUE THREAD

**Issue by rohan26062001** [Craftsmen-GDSC/craftsmen#8]
![image](https://user-images.githubusercontent.com/74822378/149646987-420b437d-4e8c-47a6-9f57-3817c3c1c006.png)

**Comment by pramod74** [comment]
Hi @rohan26062001,

I would like to take this up. From where may I get details of the additional contributors to be added to Readme.md file?

Thanks,
Pramod

**Comment by rohan26062001** [comment]
Hello @pramod74 ,
Have you registered for Diversion 2022?
